### ISSUE TITLE
Rotation and lifetime limiting for refresh tokens

### ISSUE THREAD

**Issue by andifalk** [andifalk/secure-oauth2-oidc-workshop#9]
As recommended in https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-4.12 and https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-04#section-8 the **refresh token** must be configured in Keycloak to:

- be invalidated after each usage (a new one has to be issued after each refresh token request)
- have a maximum lifetime of 24 hours
- have a total lifetime for 24 hours (i.e. after 24 hours after initial login the user has to perform complete login again)

This is an important recommendation when using refresh tokens with a SPA (and auth code + PKCE)

See [keycloak doc](https://www.keycloak.org/docs/latest/server_admin/index.html#_timeouts) section for configuring refresh token settings.

**Comment by dorianweidler** [comment]
https://msnovatec-my.sharepoint.com/:u:/g/personal/dw_novatec-gmbh_de/EW7zGeRkYglDqmQqNgxE3SwBIo8JjvjWp8-mf_oJcBRvAw?e=SNtvDv
